"""
Safety and disclaimer layer for AI-generated genetic explanations.

This module implements safety checks to ensure explanations don't contain
definitive medical language, and applies appropriate disclaimers based
on the significance of the findings.
"""

import re
from typing import List, Tuple


# Mapping of high-impact variants and genes to warning messages
HIGH_IMPACT_VARIANTS = {
    'BRCA1': "Variants in BRCA1 are associated with significantly elevated cancer risk. It is strongly recommended to discuss these results with a genetic counselor.",
    'BRCA2': "Variants in BRCA2 are associated with significantly elevated cancer risk. It is strongly recommended to discuss these results with a genetic counselor.",
    'rs429358': "APOE variants are associated with Alzheimer's disease risk. These results can have significant psychological impact. Consider speaking with a genetic counselor before reviewing.",
    'rs7412': "APOE variants are associated with Alzheimer's disease risk. These results can have significant psychological impact. Consider speaking with a genetic counselor before reviewing.",
    'TP53': "TP53 variants are associated with elevated cancer risk across multiple cancer types. Genetic counseling is strongly recommended.",
    'MLH1': "MLH1 variants are associated with Lynch syndrome and hereditary cancer risk. Genetic counseling is strongly recommended.",
    'MSH2': "MSH2 variants are associated with Lynch syndrome and hereditary cancer risk. Genetic counseling is strongly recommended.",
    'MSH6': "MSH6 variants are associated with Lynch syndrome and hereditary cancer risk. Genetic counseling is strongly recommended.",
    'PMS2': "PMS2 variants are associated with Lynch syndrome and hereditary cancer risk. Genetic counseling is strongly recommended.",
}


# Regex patterns indicating definitive medical language that should be flagged
DIAGNOSTIC_PATTERNS = [
    r'\byou have\b',
    r'\byou will develop\b',
    r'\byou are diagnosed\b',
    r'\bthis means you have\b',
    r'\byou definitely\b',
    r'\b100%\s*chance\b',
    r'\bguaranteed to\b',
    r'\bcertain to\b',
    r'\bwill certainly\b',
]


STANDARD_DISCLAIMER = """
---

**Important Disclaimer:** This explanation is for educational purposes only and should not be interpreted as medical advice. Genetic findings can be complex and may have different implications for different individuals. Always consult with a qualified healthcare provider or genetic counselor before making any health decisions based on genetic information. Allelio and its AI explanation tools do not provide medical diagnosis or treatment recommendations.
"""


def check_safety(explanation: str) -> Tuple[str, List[str]]:
    """
    Check AI-generated explanation for diagnostic language and other safety issues.
    
    Args:
        explanation: The explanation text generated by the LLM
        
    Returns:
        Tuple of (cleaned_explanation, warnings_list)
        - cleaned_explanation: The explanation with safety notices appended if needed
        - warnings_list: List of warning messages about issues found
    """
    warnings = []
    
    # Check for each diagnostic pattern
    for pattern in DIAGNOSTIC_PATTERNS:
        if re.search(pattern, explanation, re.IGNORECASE):
            warnings.append(
                "Explanation contained definitive medical language that has been flagged for review."
            )
            break  # Only add this warning once
    
    # Build result
    cleaned = explanation
    if warnings:
        caveat = "\n[Safety Note: This explanation has been flagged for potentially definitive language. Please review carefully and consult a healthcare provider.]"
        cleaned = explanation + caveat
    
    return cleaned, warnings


def get_variant_warnings(result) -> List[str]:
    """
    Check if a variant is high-impact and return appropriate warnings.
    
    Args:
        result: A VariantResult object from allelio.analysis.lookup
        
    Returns:
        List of warning strings for high-impact variants
    """
    warnings = []

    # Extract gene from clinvar or gwas entries
    gene = None
    if hasattr(result, 'clinvar_entries') and result.clinvar_entries:
        gene = getattr(result.clinvar_entries[0], 'gene', None)
    elif hasattr(result, 'gwas_entries') and result.gwas_entries:
        gene = getattr(result.gwas_entries[0], 'mapped_gene', None)

    if gene and gene in HIGH_IMPACT_VARIANTS:
        warnings.append(HIGH_IMPACT_VARIANTS[gene])

    # Check by rsID
    rsid = getattr(result, 'rsid', None)
    if rsid and rsid in HIGH_IMPACT_VARIANTS:
        warnings.append(HIGH_IMPACT_VARIANTS[rsid])

    return warnings


def wrap_with_disclaimer(explanation: str, warnings: List[str]) -> str:
    """
    Wrap an explanation with the standard disclaimer and any specific warnings.
    
    Args:
        explanation: The explanation text
        warnings: List of specific warning messages about this variant
        
    Returns:
        Wrapped explanation with disclaimers and warnings
    """
    result = explanation
    
    # Add specific warnings first
    if warnings:
        warnings_section = "\n**⚠ Important Notes:**\n"
        for warning in warnings:
            warnings_section += f"- {warning}\n"
        result = result + "\n" + warnings_section
    
    # Add standard disclaimer
    result = result + STANDARD_DISCLAIMER
    
    return result
